[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
game_token_wallet = "4qetKWMztCYZLp9zqLZiNjmnSfy13JM5VAjkKmU8g42X"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter on-chain-program-e2e run test"

[hooks]
